on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: ci

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@1.97.1
      - run: cargo build
      - run: cargo test
