name: release

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            executable: krok
            asset_name: krok-linux
          - os: macos-latest
            executable: krok
            asset_name: krok-macos
          - os: windows-latest
            executable: krok.exe
            asset_name: krok-windows

    steps:
      - name: checkout
        uses: actions/checkout@v7

      - name: enable toolchain
        uses: dtolnay/rust-toolchain@1.97.1

      - name: build
        run: cargo build --release

      - name: Set environment for github-release
        run: |
          echo "RELEASE_TAG=$( echo ${GITHUB_REF##*/} )" >> $GITHUB_ENV

      - name: create archive
        run: |
          cd target/release
          tar -czf "${{ matrix.asset_name }}-${{ env.RELEASE_TAG }}.tar.gz" "${{ matrix.executable }}"

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          draft: true
          files: |
            target/release/${{ matrix.asset_name }}-${{ env.RELEASE_TAG }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
